==== TEST RUN LOG ====
Test Name      : diamondgotcat.ypsh
Test File      : /home/runner/work/AutoTestingSystem/AutoTestingSystem/tests/diamondgotcat.ypsh.py
Command        : /opt/hostedtoolcache/Python/3.12.11/x64/bin/python /home/runner/work/AutoTestingSystem/AutoTestingSystem/tests/diamondgotcat.ypsh.py
Start (UTC)    : 2025-08-27T05:03:51.709525+00:00
Epoch (ns)     : 1756271031709506368
---- ENVIRONMENT ----
python_executable: /opt/hostedtoolcache/Python/3.12.11/x64/bin/python
python_version   : 3.12.11 (main, Jun  4 2025, 04:14:37) [GCC 11.4.0]
platform         : Linux-6.8.0-1031-azure-x86_64-with-glibc2.35
cwd              : /home/runner/work/AutoTestingSystem/AutoTestingSystem
tests_dir        : /home/runner/work/AutoTestingSystem/AutoTestingSystem/tests
os               : linux
arch             : amd64
----------------------
---- STDOUT ----

---- STDERR ----
Traceback (most recent call last):
  File "/home/runner/work/AutoTestingSystem/AutoTestingSystem/tests/diamondgotcat.ypsh.py", line 89, in <module>
    main()
  File "/home/runner/work/AutoTestingSystem/AutoTestingSystem/tests/diamondgotcat.ypsh.py", line 80, in main
    execFilePath = download_and_extract(stableTag, osname, arch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/AutoTestingSystem/AutoTestingSystem/tests/diamondgotcat.ypsh.py", line 41, in download_and_extract
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/YPSH-DGC/YPSH/releases/download/v6.5.1%0A/YPSH-linux-amd64.zip
-----------------
End   (UTC)    : 2025-08-27T05:03:52.294717+00:00
Duration (s)   : 0.585192
Return Code    : 1
======================
